#include<stdio.h>
#include<string.h>
#include<math.h>
void main()
{	int n,i,j;
//freopen("input.txt","w",stdout);
	while(scanf("%d",&n)!=EOF)
	{	if(n==0) break;
		else if(n<0)
		{   n=abs(n);
			for(j=n;j>0;j--){
			for(i=n;i>0;i--) printf("*****"); printf("\n");} //create "S"
			for(j=n;j>0;j--){
			for(i=n;i>0;i--) printf("*");
			for(i=n;i>0;i--) printf("...."); printf("\n");}
			for(j=n;j>0;j--){
			for(i=n;i>0;i--) printf("*****"); printf("\n");}
			for(j=n;j>0;j--){
			for(i=n;i>0;i--) printf("....");
			for(i=n;i>0;i--) printf("*"); printf("\n");}
			for(j=n;j>0;j--){
			for(i=n;i>0;i--) printf("*****"); printf("\n");}
			for(j=n;j>0;j--){
			for(i=n;i>0;i--) printf(".....");printf("\n");}
			for(j=n;j>0;j--){
			for(i=n;i>0;i--) printf("."); //create "A"
			for(i=n;i>0;i--) printf("***");
			for(i=n;i>0;i--) printf(".");printf("\n");}
			for(j=n;j>0;j--){
			for(i=n;i>0;i--) printf("*");
			for(i=n;i>0;i--) printf("...");
			for(i=n;i>0;i--) printf("*"); printf("\n");}
			for(j=n;j>0;j--){
			for(i=n;i>0;i--) printf("*****"); printf("\n");}
			for(j=n;j>0;j--){
			for(i=n;i>0;i--) printf("*");
			for(i=n;i>0;i--) printf("...");
			for(i=n;i>0;i--) printf("*"); printf("\n");}
			for(j=n;j>0;j--){
			for(i=n;i>0;i--) printf("*");
			for(i=n;i>0;i--) printf("...");
			for(i=n;i>0;i--) printf("*"); printf("\n");}
			for(j=n;j>0;j--){
			for(i=n;i>0;i--) printf(".....");printf("\n");}
			for(j=n;j>0;j--){
			for(i=n;i>0;i--) printf("*"); 	// "V"
			for(i=n;i>0;i--) printf("...");
			for(i=n;i>0;i--) printf("*"); printf("\n");}
			for(j=n;j>0;j--){
			for(i=n;i>0;i--) printf("*");
			for(i=n;i>0;i--) printf("...");
			for(i=n;i>0;i--) printf("*"); printf("\n");}
			for(j=n;j>0;j--){
			for(i=n;i>0;i--) printf("*");
			for(i=n;i>0;i--) printf("...");
			for(i=n;i>0;i--) printf("*"); printf("\n");}
			for(j=n;j>0;j--){
			for(i=n;i>0;i--) printf(".");
			for(i=n;i>0;i--) printf("*");
			for(i=n;i>0;i--) printf(".");
			for(i=n;i>0;i--) printf("*");
			for(i=n;i>0;i--) printf("."); printf("\n");}
			for(j=n;j>0;j--){
			for(i=n;i>0;i--) printf("..");
			for(i=n;i>0;i--) printf("*");
			for(i=n;i>0;i--) printf(".."); printf("\n");}
			for(j=n;j>0;j--){
			for(i=n;i>0;i--) printf("....."); printf("\n");}
			for(j=n;j>0;j--){
			for(i=n;i>0;i--) printf("*****"); printf("\n");} //create "E"
			for(j=n;j>0;j--){
			for(i=n;i>0;i--) printf("*");
			for(i=n;i>0;i--) printf("...."); printf("\n");}
			for(j=n;j>0;j--){
			for(i=n;i>0;i--) printf("***");
			for(i=n;i>0;i--) printf(".."); printf("\n");}
			for(j=n;j>0;j--){
			for(i=n;i>0;i--) printf("*");
			for(i=n;i>0;i--) printf("...."); printf("\n");}
			for(j=n;j>0;j--){
			for(i=n;i>0;i--) printf("*****"); printf("\n");}
			for(j=n*3;j>0;j--){
			for(i=n;i>0;i--) printf("....."); printf("\n");}//space
			for(j=n;j>0;j--){
			for(i=n;i>0;i--) printf("*"); //"H"
			for(i=n;i>0;i--) printf("...");
			for(i=n;i>0;i--) printf("*"); printf("\n");}
			for(j=n;j>0;j--){
			for(i=n;i>0;i--) printf("*");
			for(i=n;i>0;i--) printf("...");
			for(i=n;i>0;i--) printf("*"); printf("\n");}
			for(j=n;j>0;j--){
			for(i=n;i>0;i--) printf("*****"); printf("\n");}
			for(j=n;j>0;j--){
			for(i=n;i>0;i--) printf("*");
			for(i=n;i>0;i--) printf("...");
			for(i=n;i>0;i--) printf("*"); printf("\n");}
			for(j=n;j>0;j--){
			for(i=n;i>0;i--) printf("*");
			for(i=n;i>0;i--) printf("...");
			for(i=n;i>0;i--) printf("*"); printf("\n");}
			for(j=n;j>0;j--){
			for(i=n;i>0;i--) printf("....."); printf("\n");}
			for(j=n;j>0;j--){
			for(i=n;i>0;i--) printf("*****"); printf("\n");}//"R"
			for(j=n;j>0;j--){
			for(i=n;i>0;i--) printf("*");
			for(i=n;i>0;i--) printf("...");
			for(i=n;i>0;i--) printf("*"); printf("\n");}
			for(j=n;j>0;j--){
			for(i=n;i>0;i--) printf("*****"); printf("\n");}
			for(j=n;j>0;j--){
			for(i=n;i>0;i--) printf("*");
			for(i=n;i>0;i--) printf(".");
			for(i=n;i>0;i--) printf("*");
			for(i=n;i>0;i--) printf(".."); printf("\n");}
			for(j=n;j>0;j--){
			for(i=n;i>0;i--) printf("*");
			for(i=n;i>0;i--) printf("..");
			for(i=n;i>0;i--) printf("**"); printf("\n");}
			for(j=n;j>0;j--){
			for(i=n;i>0;i--) printf("....."); printf("\n");}
			for(j=n;j>0;j--){
			for(i=n;i>0;i--) printf("*****"); printf("\n");}//"I"
			for(j=n;j>0;j--){
			for(i=n;i>0;i--) printf("..");
			for(i=n;i>0;i--) printf("*");
			for(i=n;i>0;i--) printf(".."); printf("\n");}
			for(j=n;j>0;j--){
			for(i=n;i>0;i--) printf("..");
			for(i=n;i>0;i--) printf("*");
			for(i=n;i>0;i--) printf(".."); printf("\n");}
			for(j=n;j>0;j--){
			for(i=n;i>0;i--) printf("..");
			for(i=n;i>0;i--) printf("*");
			for(i=n;i>0;i--) printf(".."); printf("\n");}
			for(j=n;j>0;j--){
			for(i=n;i>0;i--) printf("*****"); printf("\n");}
			for(j=n;j>0;j--){
			for(i=n;i>0;i--) printf("....."); printf("\n");}
			for(j=n;j>0;j--){
			for(i=n;i>0;i--) printf("***"); //"D"
			for(i=n;i>0;i--) printf(".."); printf("\n");}
			for(j=n;j>0;j--){
			for(i=n;i>0;i--) printf("*");
			for(i=n;i>0;i--) printf("..");
			for(i=n;i>0;i--) printf("*");
			for(i=n;i>0;i--) printf("."); printf("\n");}
			for(j=n;j>0;j--){
			for(i=n;i>0;i--) printf("*");
			for(i=n;i>0;i--) printf("...");
			for(i=n;i>0;i--) printf("*"); printf("\n");}
			for(j=n;j>0;j--){
			for(i=n;i>0;i--) printf("*");
			for(i=n;i>0;i--) printf("..");
			for(i=n;i>0;i--) printf("*");
			for(i=n;i>0;i--) printf("."); printf("\n");}
			for(j=n;j>0;j--){
			for(i=n;i>0;i--) printf("***");
			for(i=n;i>0;i--) printf(".."); printf("\n");}
			for(j=n;j>0;j--){
			for(i=n;i>0;i--) printf("....."); printf("\n");}
			for(j=n;j>0;j--){
			for(i=n;i>0;i--) printf("*****"); printf("\n");}//"O"
			for(j=n;j>0;j--){
			for(i=n;i>0;i--) printf("*");
			for(i=n;i>0;i--) printf("...");
			for(i=n;i>0;i--) printf("*"); printf("\n");}
			for(j=n;j>0;j--){
			for(i=n;i>0;i--) printf("*");
			for(i=n;i>0;i--) printf("...");
			for(i=n;i>0;i--) printf("*"); printf("\n");}
			for(j=n;j>0;j--){
			for(i=n;i>0;i--) printf("*");
			for(i=n;i>0;i--) printf("...");
			for(i=n;i>0;i--) printf("*"); printf("\n");}
			for(j=n;j>0;j--){
			for(i=n;i>0;i--) printf("*****"); printf("\n");}
			for(j=n;j>0;j--){
			for(i=n;i>0;i--) printf("....."); printf("\n");}
			for(j=n;j>0;j--){
			for(i=n;i>0;i--) printf("*");   //"Y"
			for(i=n;i>0;i--) printf("...");
			for(i=n;i>0;i--) printf("*"); printf("\n");}
			for(j=n;j>0;j--){
			for(i=n;i>0;i--) printf(".");
			for(i=n;i>0;i--) printf("*");
			for(i=n;i>0;i--) printf(".");
			for(i=n;i>0;i--) printf("*");
			for(i=n;i>0;i--) printf(".");   printf("\n");}
			for(j=n;j>0;j--){
			for(i=n;i>0;i--) printf("..");
			for(i=n;i>0;i--) printf("*");
			for(i=n;i>0;i--) printf(".."); printf("\n");}
			for(j=n;j>0;j--){
			for(i=n;i>0;i--) printf("..");
			for(i=n;i>0;i--) printf("*");
			for(i=n;i>0;i--) printf(".."); printf("\n");}
			for(j=n;j>0;j--){
			for(i=n;i>0;i--) printf("..");
			for(i=n;i>0;i--) printf("*");
			for(i=n;i>0;i--) printf(".."); printf("\n");}
		}
		else
		{
		for(j=n;j>0;j--)
		{	for(i=n;i>0;i--) printf("*****");
			for(i=n;i>0;i--) printf("..");
			for(i=n;i>0;i--) printf("***");
			for(i=n;i>0;i--) printf("..");
			for(i=n;i>0;i--) printf("*");
			for(i=n;i>0;i--) printf("...");
			for(i=n;i>0;i--) printf("*");
			for(i=n;i>0;i--) printf(".");
			for(i=n;i>0;i--) printf("*****");
			for(i=n;i>0;i--) printf("...");
			for(i=n;i>0;i--) printf("*");
			for(i=n;i>0;i--) printf("...");
			for(i=n;i>0;i--) printf("*");
			for(i=n;i>0;i--) printf(".");
			for(i=n;i>0;i--) printf("*****");
			for(i=n;i>0;i--) printf(".");
			for(i=n;i>0;i--) printf("*****");
			for(i=n;i>0;i--) printf(".");
			for(i=n;i>0;i--) printf("***");
			for(i=n;i>0;i--) printf("...");
			for(i=n;i>0;i--) printf("*****");
			for(i=n;i>0;i--) printf(".");
			for(i=n;i>0;i--) printf("*");
			for(i=n;i>0;i--) printf("...");
			for(i=n;i>0;i--) printf("*");
			printf("\n");
		}
		for(j=n;j>0;j--)
		{	for(i=n;i>0;i--) printf("*");
			for(i=n;i>0;i--) printf(".....");
			for(i=n;i>0;i--) printf("*");
			for(i=n;i>0;i--) printf("...");
			for(i=n;i>0;i--) printf("*");
			for(i=n;i>0;i--) printf(".");
			for(i=n;i>0;i--) printf("*");
			for(i=n;i>0;i--) printf("...");
			for(i=n;i>0;i--) printf("*");
			for(i=n;i>0;i--) printf(".");
			for(i=n;i>0;i--) printf("*");
			for(i=n;i>0;i--) printf(".......");
			for(i=n;i>0;i--) printf("*");
			for(i=n;i>0;i--) printf("...");
			for(i=n;i>0;i--) printf("*");
			for(i=n;i>0;i--) printf(".");
			for(i=n;i>0;i--) printf("*");
			for(i=n;i>0;i--) printf("...");
			for(i=n;i>0;i--) printf("*");
			for(i=n;i>0;i--) printf("...");
			for(i=n;i>0;i--) printf("*");
			for(i=n;i>0;i--) printf("...");
			for(i=n;i>0;i--) printf("*");
			for(i=n;i>0;i--) printf("..");
			for(i=n;i>0;i--) printf("*");
			for(i=n;i>0;i--) printf("..");
			for(i=n;i>0;i--) printf("*");
			for(i=n;i>0;i--) printf("...");
			for(i=n;i>0;i--) printf("*");
			for(i=n;i>0;i--) printf("..");
			for(i=n;i>0;i--) printf("*");
			for(i=n;i>0;i--) printf(".");
			for(i=n;i>0;i--) printf("*");
			for(i=n;i>0;i--) printf(".");
			printf("\n");
		}
		for(j=n;j>0;j--)
		{	for(i=n;i>0;i--) printf("*****");
			for(i=n;i>0;i--) printf(".");
			for(i=n;i>0;i--) printf("*****");
			for(i=n;i>0;i--) printf(".");
			for(i=n;i>0;i--) printf("*");
			for(i=n;i>0;i--) printf("...");
			for(i=n;i>0;i--) printf("*");
			for(i=n;i>0;i--) printf(".");
			for(i=n;i>0;i--) printf("***");
			for(i=n;i>0;i--) printf(".....");
			for(i=n;i>0;i--) printf("*****");
			for(i=n;i>0;i--) printf(".");
			for(i=n;i>0;i--) printf("*****");
			for(i=n;i>0;i--) printf("...");
			for(i=n;i>0;i--) printf("*");
			for(i=n;i>0;i--) printf("...");
			for(i=n;i>0;i--) printf("*");
			for(i=n;i>0;i--) printf("...");
			for(i=n;i>0;i--) printf("*");
			for(i=n;i>0;i--) printf(".");
			for(i=n;i>0;i--) printf("*");
			for(i=n;i>0;i--) printf("...");
			for(i=n;i>0;i--) printf("*");
			for(i=n;i>0;i--) printf("...");
			for(i=n;i>0;i--) printf("*");
			for(i=n;i>0;i--) printf("..");
			printf("\n");
		}
		for(j=n;j>0;j--)
		{	for(i=n;i>0;i--) printf("....");
			for(i=n;i>0;i--) printf("*");
			for(i=n;i>0;i--) printf(".");
			for(i=n;i>0;i--) printf("*");
			for(i=n;i>0;i--) printf("...");
			for(i=n;i>0;i--) printf("*");
			for(i=n;i>0;i--) printf("..");
			for(i=n;i>0;i--) printf("*");
			for(i=n;i>0;i--) printf(".");
			for(i=n;i>0;i--) printf("*");
			for(i=n;i>0;i--) printf("..");
			for(i=n;i>0;i--) printf("*");
			for(i=n;i>0;i--) printf(".......");
			for(i=n;i>0;i--) printf("*");
			for(i=n;i>0;i--) printf("...");
			for(i=n;i>0;i--) printf("*");
			for(i=n;i>0;i--) printf(".");
			for(i=n;i>0;i--) printf("*");
			for(i=n;i>0;i--) printf(".");
			for(i=n;i>0;i--) printf("*");
			for(i=n;i>0;i--) printf(".....");
			for(i=n;i>0;i--) printf("*");
			for(i=n;i>0;i--) printf("...");
			for(i=n;i>0;i--) printf("*");
			for(i=n;i>0;i--) printf("..");
			for(i=n;i>0;i--) printf("*");
			for(i=n;i>0;i--) printf("..");
			for(i=n;i>0;i--) printf("*");
			for(i=n;i>0;i--) printf("...");
			for(i=n;i>0;i--) printf("*");
			for(i=n;i>0;i--) printf("...");
			for(i=n;i>0;i--) printf("*");
			for(i=n;i>0;i--) printf("..");
			printf("\n");
		}
		for(j=n;j>0;j--)
		{	for(i=n;i>0;i--) printf("*****");
			for(i=n;i>0;i--) printf(".");
			for(i=n;i>0;i--) printf("*");
			for(i=n;i>0;i--) printf("...");
			for(i=n;i>0;i--) printf("*");
			for(i=n;i>0;i--) printf("...");
			for(i=n;i>0;i--) printf("*");
			for(i=n;i>0;i--) printf("...");
			for(i=n;i>0;i--) printf("*****");
			for(i=n;i>0;i--) printf("...");
			for(i=n;i>0;i--) printf("*");
			for(i=n;i>0;i--) printf("...");
			for(i=n;i>0;i--) printf("*");
			for(i=n;i>0;i--) printf(".");
			for(i=n;i>0;i--) printf("*");
			for(i=n;i>0;i--) printf("..");
			for(i=n;i>0;i--) printf("**");
			for(i=n;i>0;i--) printf(".");
			for(i=n;i>0;i--) printf("*****");
			for(i=n;i>0;i--) printf(".");
			for(i=n;i>0;i--) printf("***");
			for(i=n;i>0;i--) printf("...");
			for(i=n;i>0;i--) printf("*****");
			for(i=n;i>0;i--) printf("...");
			for(i=n;i>0;i--) printf("*");
			for(i=n;i>0;i--) printf("..");
			printf("\n");
		}
		}printf("\n\n");
	}

//***** . .***. . *...* . ***** ... *...* . ***** . ***** . ***.. . ***** . *...*
//*.... . *...* . *...* . *.... ... *...* . *...* . ..*.. . *..*. . *...* . .*.*.
//***** . ***** . *...* . ***.. ... ***** . ***** . ..*.. . *...* . *...* . ..*..
//....* . *...* . .*.*. . *.... ... *...* . *.*.. . ..*.. . *..*. . *...* . ..*..
//***** . *...* . ..*.. . ***** ... *...* . *..** . ***** . ***.. . ***** . ..*..
}