#include<stdio.h>
#include<math.h>
void main()
{	/*double i,n=1498,x;
	for(i=853183456,x=i;n<1500;i++,x=i)
	{    for(;fmod(x,2)==0;x/=2);
		for(;fmod(x,3)==0;x/=3);
		for(;fmod(x,5)==0;x/=5); //*/
		/*for(;x%2==0;x/=2);
		for(;x%3==0;x/=3);
		for(;x%5==0;x/=5);     //*/
	/* 	if(x==1) n++;
	}  printf("The 1500'th ugly number is %.0lf.",i-1); //*/
	printf("The 1500'th ugly number is 859963392.\n");
}//m